import type { NextPage } from "next";
import { useRef, useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSound from "use-sound";
import ScrollAnimation from "react-animate-on-scroll";
import "animate.css/animate.min.css";

import { Interviews } from "../components/Interviews";
import Link from "next/link";

const BoopButton = () => {
  const [play] = useSound("/boopSfx");

  return <button onClick={play}>Boop!</button>;
};

const Home: NextPage = () => {
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-hidden">
        <PanelOne />
        <PanelTwo />
        <PanelThree />
        <PanelFour />
        <PanelFive />
        <PanelSix />
        <PanelSeven />
        <PanelEight />
        <PanelNine />
        <PanelTen />
        <PanelEleven />
        <PanelTwelve />
        <PanelThirteen />
        <Interviews />
      </main>
    </div>
  );
};

const PanelOne = () => {
  const [height, setHeight] = useState(0);

  useEffect(() => {
    setHeight(window.innerHeight);
  });

  return (
    <FadeInSection>
      <div className="w-full relative h-screen flex flex-col justify-center items-center">
        <div className="w-2/3">
          <p className="font-winnieyoe text-3xl text-center">
            Anonymous contributor C is an engineer who has recently started
            their advocacy work, connecting with other community members and
            sharing community events and updates through their platform.
          </p>
        </div>
      </div>
    </FadeInSection>
  );
};

const PanelTwo = () => {
  return (
    <div className="w-full relative bg-[#F2F2F2] h-screen">
      <div>
        <p className="font-winnieyoe text-3xl">
          My grandmother lived in Chung Pak and passed away 1.5 months agao. I
          found out about the jail when I went to her funeral.
        </p>
      </div>
      <div className="">
        <FadeInSection>
          <Image
            src="/2.png"
            alt=""
            layout="responsive"
            width={1440}
            height={549}
          />
        </FadeInSection>
      </div>
      <div>
        <p className="font-winnieyoe text-3xl">
          Chinatown was my second home. I spent many weekends here visitng my
          grandmother and going to church.
        </p>
      </div>
    </div>
  );
};

const PanelThree = () => {
  return (
    <FadeInSection>
      <div className="w-full relative bg-white h-screen flex flex-col">
        <div>
          <p className="font-winnieyoe text-3xl">
            Working to fight for Chinatown consumes every premise of my life.
            I’m not exercising, I barely sleep.
          </p>
        </div>
        <div className="w-1/2 m-auto items-center">
          <Image
            src="/3.png"
            alt=""
            layout="responsive"
            width={942}
            height={748}
          />
        </div>
        <div>
          <p className="font-winnieyoe text-2xl">
            My husband and I are trying to have a kid later this year but I keep
            thinking, how am I supposed to fight for Chinatown and try to have a
            kid?
          </p>
        </div>
      </div>
    </FadeInSection>
  );
};

const PanelFour = () => {
  return (
    <div className="w-full relative bg-[#F2F2F2] h-screen flex flex-col justify-center items-center">
      <div>
        <p className="font-winnieyoe text-3xl">
          This is the city’s first design-build rather than design-bid-build
          project, so we don’t have any idea what the design is.
        </p>
      </div>
      <div className="w-1/2">
        <FadeInSection>
          <Image
            src="/4.png"
            alt=""
            layout="responsive"
            width={977}
            height={600}
          />
        </FadeInSection>
      </div>
    </div>
  );
};

const PanelFive = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div>
        <p className="font-winnieyoe text-3xl">
          There’s water in the soil of Canal street that would need to be pumped
          out, that’s actually really risky. Pile driving is about 120 decibels,
          how are they going to mitigate that? How can the businesses and the
          citizens in the building survive? I don’t get it.
        </p>
      </div>
    </div>
  );
};

const PanelSix = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div className="w-2/3">
        <p className="font-winnieyoe text-3xl">
          Rikers is supposed to close as a prison by August 31, 2027. The city
          is pushing everything through carelessly because delays are costly..
          I’m now trying to think through how to change the law.
        </p>
      </div>
    </div>
  );
};

const PanelSeven = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div className="w-2/3">
        <p className="font-winnieyoe text-3xl">
          I started my platform to teach people the story, the history. I just
          finished this page I’ll post on the site.
        </p>
      </div>
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div className="w-2/3">
        <p className="font-winnieyoe text-3xl">
          I also wanted to build out an email form that allows people to find
          who to email to get attention on different issues.
        </p>
      </div>
    </div>
  );
};

const PanelEight = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div>
        <p className="font-winnieyoe text-3xl">
          Until recently, The people fighting the jails and fighting the
          shelters aren’t helping the other. A lot of the shelter language is
          viewed as NIMBY while some view the jail as a done deal.
        </p>
      </div>
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div>
        <p className="font-winnieyoe text-3xl">
          If you zoomed out far enough it’s the same story, it’s a story of
          institutionalized hate and pushing through things to Chinatown because
          people don’t have a voice. That’s the story.
        </p>
      </div>
    </div>
  );
};

const PanelNine = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div>
        <p className="font-winnieyoe text-3xl">
          A lot of people in Chinatown are Chinese speaking people who didn’t
          know what’s going on. There's a whole group of people that I feel is
          untapped. So I'm trying to connect the three Chinatown, Brooklyn, and
          Queens.
        </p>
      </div>
    </div>
  );
};

const PanelTen = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div>
        <p className="font-winnieyoe text-3xl">
          Until recently, The people fighting the jails and fighting the
          shelters aren’t helping the other. A lot of the shelter language is
          viewed as NIMBY while some view the jail as a done deal.
        </p>
      </div>
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div>
        <p className="font-winnieyoe text-3xl">
          If you zoomed out far enough it’s the same story, it’s a story of
          institutionalized hate and pushing through things to Chinatown because
          people don’t have a voice. That’s the story.
        </p>
      </div>
    </div>
  );
};

const PanelEleven = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div>
        <p className="font-winnieyoe text-3xl">
          Until recently, The people fighting the jails and fighting the
          shelters aren’t helping the other. A lot of the shelter language is
          viewed as NIMBY while some view the jail as a done deal.
        </p>
      </div>
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div>
        <p className="font-winnieyoe text-3xl">
        I have an idea in May to book out Madison Square Garden or Barclays Center and throw a massive rally bring in Asian performers.

“Can you hear us now? Are you scared now?
        </p>
      </div>
    </div>
  );
};

const PanelTwelve = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div>
        <p className="font-winnieyoe text-3xl">
        People are pushing for criminal justice reform, people also want to help the homeless. We want all these other things too, within Chinatown, it was just like, can you help us too?
        </p>
      </div>
    </div>
  );
};

const PanelThirteen = () => {
  return (
    <div className="w-full h-screen relative flex flex-col justify-center items-center">
      <div className="w-2/3">
        <FadeInSection>
          <Image
            src="/5.png"
            alt=""
            layout="responsive"
            width={961}
            height={638}
          />
        </FadeInSection>
      </div>
      <div>
        <p className="font-winnieyoe text-3xl">
        You’re pro closing Rikers, are you also pro protecting the marginalized people of Chinatown? 
        </p>
      </div>
    </div>
  );
};

function FadeInSection(props) {
  const [isVisible, setVisible] = useState(true);
  const domRef = useRef();
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => setVisible(entry.isIntersecting));
    });
    observer.observe(domRef.current);
    // return () => observer.unobserve(domRef.current);
  }, []);
  return (
    <div
      className={`fade-in-section ${isVisible ? "is-visible" : ""}`}
      ref={domRef}
    >
      {props.children}
    </div>
  );
}


function DelayFadeInSection(props) {
  const [isVisible, setVisible] = useState(true);
  const domRef = useRef();
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => setVisible(entry.isIntersecting));
    });
    observer.observe(domRef.current);
    // return () => observer.unobserve(domRef.current);
  }, []);
  return (
    <div
      className={`delay-fade-in-section ${isVisible ? "is-visible" : ""}`}
      ref={domRef}
    >
      {props.children}
    </div>
  );
}

const AudioIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    version="1.0"
    width="500"
    height="500"
    viewBox="0 0 75 75"
  >
    <path
      d="M39.389,13.769 L22.235,28.606 L6,28.606 L6,47.699 L21.989,47.699 L39.389,62.75 L39.389,13.769z"
      style="stroke:#111;stroke-width:5;stroke-linejoin:round;fill:#111;"
    />
    <path
      d="M48,27.6a19.5,19.5 0 0 1 0,21.4M55.1,20.5a30,30 0 0 1 0,35.6M61.6,14a38.8,38.8 0 0 1 0,48.6"
      style="fill:none;stroke:#111;stroke-width:5;stroke-linecap:round"
    />
  </svg>
);

export default Home;
